#!/usr/bin/env python3
"""plan-v6.1 E4b — a deterministic {sub-vendor prose string -> vendors.id} FK map.

The 999 sub-markets carry vendor names as PROSE (`sub.vendors[]`). This resolves each unique
string to a real vendors.id — DETERMINISTICALLY, zero model tokens — and writes the map to
data/sub_vendor_fk.yaml. NON-DESTRUCTIVE: taxonomy.yaml keeps its prose; the app reads this map
to link sub vendors like category vendors (drawer / #v/ deep-link).

Discipline (E4a): resolve ONLY on a confident match — exact slug, unique normalized name, a
vendor-name prefix (for "Vendor Product" strings), or the exact-company tiebreak. Ambiguous or
absent -> omitted from the map + logged to private/unresolved-sub-vendors.txt. NEVER invents a slug.
Most sub vendors are companies NOT in the 309-vendor registry — those stay unmapped by design.

Run: python3 tools/build_sub_vendor_fk.py
"""
import re
import sys
from collections import Counter
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "data"
OUT = DATA / "sub_vendor_fk.yaml"
UNRESOLVED = REPO / "private" / "unresolved-sub-vendors.txt"

sys.path.insert(0, str(Path(__file__).resolve().parent))  # tools/ for lib.load
from lib.load import all_vendors  # resolve against curated + provisional vendor tiers


def norm(v):
    v = re.split(r"[(/—]", str(v))[0].lower()
    v = re.sub(r"\b(inc|llc|ltd|gmbh|corp|co|sa|ag|plc|the)\b", "", v)
    return re.sub(r"[^a-z0-9]+", " ", v).strip()


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", str(s).lower()).strip("-")


def load_aliases():
    """hand-authored overrides for ambiguous cases the matcher can't resolve (e.g. "Thermo Fisher"
    when 2 vendor ids share the prefix). data/vendor_aliases.yaml: {aliases: {prose-or-norm: vendor_id}}."""
    p = DATA / "vendor_aliases.yaml"
    if not p.exists():
        return {}
    return (yaml.safe_load(p.read_text(encoding="utf-8")) or {}).get("aliases", {}) or {}


def build_fk(vendors, subs, aliases=None):
    """PURE — resolve every sub-vendor prose string to a vendor id. Returns (fk, uniq, mentions).
    No file write, so tests can re-derive and check for staleness."""
    aliases = aliases or {}
    id_set = {v["id"] for v in vendors}
    vnorm = {}
    for v in vendors:
        vnorm.setdefault(norm(v["name"]), set()).add(v["id"])
    prefixes = {nv: ids for nv, ids in vnorm.items() if len(nv) >= 6}  # avoid "ge"/"hp" noise

    def resolve(strn):
        if strn in aliases:          # hand-authored alias wins (#8: ambiguous cases)
            return aliases[strn]
        ns = norm(strn)              # company part (norm strips at "(")
        if ns in aliases:
            return aliases[ns]
        cs = slug(ns)                # company-part slug
        cands = set()
        if slug(strn) in id_set:
            cands.add(slug(strn))
        if cs in id_set:             # company-part slug -> matches fuller stored names
            cands.add(cs)
        cands |= vnorm.get(ns, set())
        for nv, ids in prefixes.items():
            if ns == nv or ns.startswith(nv + " "):
                cands |= ids
        # company slug is a UNIQUE hyphen-prefix of a vendor id: "Baxter" -> baxter-international.
        if cs and len(cs) >= 4 and cs not in cands:
            pref = [i for i in id_set if i == cs or i.startswith(cs + "-")]
            if len(pref) == 1:
                cands.add(pref[0])
        exact, comp = slug(strn), cs
        if exact in cands:
            return exact
        if comp in cands:
            return comp
        return next(iter(cands)) if len(cands) == 1 else None

    mentions = [str(vn) for s in subs for vn in (s.get("vendors") or [])]
    uniq = Counter(mentions)
    fk = {strn: resolve(strn) for strn in uniq}
    fk = {k: v for k, v in fk.items() if v}
    return fk, uniq, mentions


def main():
    vendors = all_vendors()  # curated + provisional
    subs = yaml.safe_load((DATA / "taxonomy.yaml").read_text(encoding="utf-8")).get("subcategories", [])
    fk, uniq, mentions = build_fk(vendors, subs, load_aliases())
    resolved_mentions = sum(uniq[s] for s in fk)
    # deterministic + stable output (block mapping, sorted keys — safe_dump handles quoting)
    doc = {"version": 1, "generated_by": "tools/build_sub_vendor_fk.py",
           "counts": {"unique_strings": len(uniq), "resolved": len(fk),
                      "total_mentions": len(mentions), "resolved_mentions": resolved_mentions},
           "map": dict(sorted(fk.items()))}
    OUT.write_text(
        "# GENERATED by tools/build_sub_vendor_fk.py — do not hand-edit. Rebuild after taxonomy/vendors change.\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8")

    unres = sorted((uniq[s], s) for s in uniq if s not in fk)
    UNRESOLVED.parent.mkdir(exist_ok=True)
    UNRESOLVED.write_text("\n".join(f"{n:4d}  {s}" for n, s in sorted(unres, reverse=True)) + "\n",
                          encoding="utf-8")

    pctu = 100 * len(fk) // max(1, len(uniq))
    pctm = 100 * resolved_mentions // max(1, len(mentions))
    print(f"[sub_vendor_fk] {len(fk)}/{len(uniq)} unique strings resolved ({pctu}%); "
          f"{resolved_mentions}/{len(mentions)} mentions ({pctm}%); "
          f"{len(uniq) - len(fk)} unresolved -> {UNRESOLVED.relative_to(REPO)}", file=sys.stderr)


if __name__ == "__main__":
    main()
